source 'https://rubygems.org'

# Specify your gem's dependencies in webmate.gemspec
gemspec

gem 'em-synchrony'
gem 'rack-contrib'
gem 'sinatra'
gem 'sinatra-synchrony'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'yajl-ruby'
gem 'configatron'