source 'https://rubygems.org'

# Specify your gem's dependencies in webmate.gemspec
gemspec

gem 'sinatra'
gem 'sinatra-synchrony'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'thin'
gem 'yajl-ruby'
gem 'configatron'
gem 'slim'

group :assets do
  gem 'therubyracer', '0.10.2'
  gem 'alphasights-sinatra-sprockets', require: 'sinatra-sprockets',
      git: 'git://github.com/droidlabs/sinatra-sprockets.git'
  gem 'closure-compiler'
  gem 'yui-compressor'
  gem 'coffee-script'
end

group :test do
  gem 'rspec'
  gem 'rack-test', :require => "rack/test"
end